### ISSUE TITLE
make this library side-effect free on importing

### ISSUE THREAD

**Issue by trim21** [libp2p/go-libp2p-asn-util#15]
Do not initialize `Store` on importing,  use `sync.Once` so it could be initialized at the first time someone would use it.

https://github.com/libp2p/go-libp2p-asn-util/blob/54e13735517a9edc903662fa208bec726bdc8e98/asn.go#L13-L15

It may be imported by the downstream users, but maybe not be used every time.

**Comment by stv0g** [comment]
Yes, init consumes about 4,6 MiB of memory on importing which could be saved

**Comment by MarcoPolo** [comment]
I'm not sure we can make this change without affecting the core semantics of this library. Existing users rely on this behavior and we could break them in subtle, hard to debug, ways.

This library itself imports a 2.5MB generated go file (ipv6_asn_map.gen.go), and what init does is fill the `cidranger.NewPCTrieRanger` datastructure. While an argument could be made that we could fill this datastructure when requested, I think it makes sense to parse the generated go file into the var on init since this is the whole point of this library. You only use this library when you need to use this datastructure.

Maybe in the ideal world we could do this at compile time, but in Go `init` is the tool for this.

Closing since I think the request here would change the library into a different one. (but please comment with your use case if you have a specific use case in mind that is blocked by this).

**Comment by stv0g** [comment]
@MarcoPolo Can we keep this on the roadmap for the next upcoming major version of the package?

**Comment by marten-seemann** [comment]
@stv0g Can you explain why the current state poses a problem for you?

**Comment by stv0g** [comment]
I stumbled upon this behaviour while profiling my code for memory consumption.
An this little package contributed over 2 thirds of it.

**Comment by marten-seemann** [comment]
That wouldn't change if we didn't load the table on `init` though. The ASN tables are big (see https://iptoasn.com/), and if your application needs them, there's no reasonable way to use them without loading them into memory. 
If your application doesn't need them, there's no need to import this package in the first place.
